### ISSUE TITLE
Cannot build the minimal set of components without Docker (step 4): possible component version conflict

### ISSUE THREAD

**Issue by YanaPalacheva** [WDAqua/Qanary-question-answering-components#127]
Hello!

I'm trying to build and run a template QA system following steps from the readme. I have problems with step 4:
`mvn clean package -Ddockerfile.skip=true -P tinytutorial`

The build fails, I receive the following error:

```
[ERROR] Failed to execute goal on project qa.NED-DBpedia-Spotlight: Could not resolve dependencies for project eu.wdaqua.qanary.component:qa.NED-DBpedia-Spotlight:jar:2.2.1: 
Failed to collect dependencies at eu.wdaqua.qanary:qa.component:jar:[2.1.1,3.0.0): No versions available for eu.wdaqua.qanary:qa.component:jar:[2.1.1,3.0.0) within specified range -> [Help 1]

```

I have up and running QanaryPipeline v3.1.0. So, I tried to extend the range manually in [the corresponding pom-file](https://github.com/WDAqua/Qanary-question-answering-components/blob/master/qanary_component-NED-DBpedia-Spotlight/pom.xml):
from `<qanary.version>[2.1.1,3.0.0)</qanary.version>` (line 17) to `<qanary.version>[2.1.1,3.1.0]</qanary.version>`
and got a new set of errors after a while:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test) on project qa.NED-DBpedia-Spotlight: There are test failures.
[ERROR] Please refer to /home/yana/Documents/nl2sparql/qanary_env/Qanary-question-answering-components/qanary_component-NED-DBpedia-Spotlight/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
```

The referred surefire-reports contains the following text file:

> Test set: eu.wdaqua.qanary.spotlightNED.TestQanaryServiceController
> Tests run: 3, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 5.972 s <<< FAILURE! - in eu.wdaqua.qanary.spotlightNED.TestQanaryServiceController
> testDescriptionAvailable(eu.wdaqua.qanary.spotlightNED.TestQanaryServiceController)  Time elapsed: 0.039 s  <<< FAILURE!
> java.lang.AssertionError: Status expected:<200> but was:<404>
> 	at eu.wdaqua.qanary.spotlightNED.TestQanaryServiceController.testDescriptionAvailable(TestQanaryServiceController.java:77)

My system configs:

```
(base) yana@yana-debian:/$ lsb_release -drc
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

(base) yana@yana-debian:/$ java --version
openjdk 11.0.14 2022-01-18
OpenJDK Runtime Environment (build 11.0.14+9-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.14+9-post-Debian-1deb10u1, mixed mode, sharing)

(base) yana@yana-debian:/$ mvn --version
Apache Maven 3.6.0
Maven home: /usr/share/maven
Java version: 11.0.14, vendor: Debian, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.19.0-12-amd64", arch: "amd64", family: "unix"
```

Thank you for your help in advance ^^

**Comment by Perevalov** [comment]
Hello @YanaPalacheva, it still may take some time to investigate the problem. I'd recommend to use the docker image with the following configuration as a temporal solution:

```yml
  dbpedia-spotlight-ned:
    image: qanary/qanary_component-ned-dbpedia-spotlight:3.0.0
    ports:
      - componentPort:componentPort
    restart: unless-stopped
    environment:
      - SERVER_PORT=componentPort
      - SPRING_BOOT_ADMIN_URL=http://pipelineHost:pipelinePort
      - SERVER_HOST=http://pipelineHost
      - SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE-BASE-URL=http://componentHost:componentPort
```

**Comment by YanaPalacheva** [comment]
Hi!
 
 Maybe I misunderstand something, but when I try to replace the host and port value in the template you provided me with, nothing happens (meaning, `docker-compose up` is valid, the application seems to be up, but there's no changes in the user interface on http://localhost:8080/startquestionansweringwithtextquestion - no available components are listed).
 
 I got that pipelineHost=localhost, pipelinePort=8080 (where the Qanary Core lives), but what are the component properties? I tried a random port (8085) and localhost but it doesn't seem to be the case:
 
docker-compose.yaml
```
  dbpedia-spotlight-ned:
    image: qanary/qanary_component-ned-dbpedia-spotlight:3.0.0
    ports:
      - 8085:8085
    restart: unless-stopped
    environment:
      - SERVER_PORT=8085
      - SPRING_BOOT_ADMIN_URL=http://localhost:8080
      - SERVER_HOST=http://localhost
      - SPRING_BOOT_ADMIN_CLIENT_INSTANCE_SERVICE-BASE-URL=http://localhost:8085
```

The last line of the log after running `docker-compose up` is this:
`dbpedia-spotlight-ned_1  | 2022-05-19 11:39:54.234  WARN 1 --- [gistrationTask1] d.c.b.a.c.r.ApplicationRegistrator       : Failed to register application as Application(name=NED-DBpediaSpotlight, managementUrl=http://localhost:8080/actuator, healthUrl=http://localhost:8080/actuator/health, serviceUrl=http://localhost:8080/) at spring-boot-admin ([http://localhost:8080/instances]): 404 : [{"timestamp":"2022-05-19T11:39:54.207+00:00","status":404,"error":"Not Found","path":"/instances"}]. Further attempts are logged on DEBUG level`

Thanks in advance!
